### ISSUE TITLE
can't mapping request

### ISSUE THREAD

**Issue by alamhubb** [bamiidowu/spring-boot-legacy-weblogic#2]
http://....:7001/spring-boot-legacy-weblogic/
is ok;
return Hello World!;

but other request can't mapping

@RequestMapping("/1")
	@ResponseBody
	public String ok1() {
		return "ok";
	}

http://....:7001/spring-boot-legacy-weblogic/1

Error 404--Not Found

From RFC 2068 Hypertext Transfer Protocol -- HTTP/1.1:

10.4.5 404 Not Found

The server has not found anything matching the Request-URI. No indication is given of whether the condition is temporary or permanent.

If the server does not wish to make this information available to the client, the status code 403 (Forbidden) can be used instead. The 410 (Gone) status code SHOULD be used if the server knows, through some internally configurable mechanism, that an old resource is permanently unavailable and has no forwarding address.

**Comment by bahcetepe** [comment]
Maybe it helps for others, you should put @ComponentScan on top of SpringBootWebLogicLegacyApplication.

**Comment by zygimantus** [comment]
@qinkaiyuan, you should close this issue. @bahcetepe answer solved it.

**Comment by bamiidowu** [comment]
Thanks bahcetepe. I'll make the change. It's nice to see people are finding this useful.
